#!/bin/bash

# Ordem corrigida por dependência
PACKAGES=(
    "my_px4_interfaces"
    "px4_msgs"
    "px4_ros_com"
    "missions"
    "coletor"
    "swarm_drone"
)

echo "Iniciando compilação individual com limite de hardware..."
echo "--------------------------------------------"

for PKG in "${PACKAGES[@]}"
do
    echo "==> Compilando: $PKG"
    
    # --parallel-workers 1: Compila um pacote por vez
    # --executor sequential: Processa as tarefas internas uma após a outra
    # --cmake-args -DCMAKE_BUILD_TYPE=Release: Usa menos memória que o modo Debug
    colcon build --symlink-install \
                 --packages-select "$PKG" \
                 --parallel-workers 1 \
                 --executor sequential \
                 --cmake-args -DCMAKE_BUILD_TYPE=Release

    if [ $? -eq 0 ]; then
        echo "Successfully built: $PKG"
    else
        echo "Error building: $PKG. Aborting."
        exit 1
    fi
    echo "--------------------------------------------"
done

echo "Todos os pacotes foram processados!"
source install/setup.bash