#!/bin/bash

# Lista dos pacotes para compilar
PACKAGES=(
    "coletor"
    "missions"
    "my_px4_interfaces"
    "px4_msgs"
    "px4_ros_com"
    "swarm_drone"
)

echo "Iniciando compilação individual dos pacotes..."
echo "--------------------------------------------"

# Loop através da lista
for PKG in "${PACKAGES[@]}"
do
    echo "==> Compilando: $PKG"
    
    # Executa o colcon para o pacote específico
    # --symlink-install: evita ter que recompilar para mudanças em scripts python/arquivos de config
    # --packages-select: filtra apenas o pacote desejado
    colcon build --symlink-install --packages-select "$PKG"
    
    # Verifica se a compilação do pacote anterior teve sucesso
    if [ $? -eq 0 ]; then
        echo "Successfully built: $PKG"
    else
        echo "Error building: $PKG. Aborting script."
        exit 1
    fi
    echo "--------------------------------------------"
done

echo "Todos os pacotes foram processados!"
source install/setup.bash